### ISSUE TITLE
Bug: link error from the python binding 

### ISSUE THREAD

**Issue by 813ethan** [ZCG-coder/Steppable#6]
## Details

libpython3.11.so is not being linked to the binding 

error happened when importing the library in python:
`ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/home/Steppable/build/temp.linux-aarch64-cpython-311/steppyble/lib/steppyble.cpython-311.so"...`

a readelf -d to the library:
```Dynamic section at offset 0x7889c8 contains 28 entries:
  Tag        Type                         Name/Value
 0x000000000000001d (RUNPATH)            Library runpath: [/data/data/com.termux/files/usr/lib]
 0x0000000000000001 (NEEDED)             Shared library: [libc++_shared.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x0000000000000007 (RELA)               0xdb68
 0x0000000000000008 (RELASZ)             12672 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          122
 0x0000000000000017 (JMPREL)             0x10ce8
 0x0000000000000002 (PLTRELSZ)           8160 (bytes)
 0x0000000000000003 (PLTGOT)             0x5c7b0
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000006 (SYMTAB)             0x308
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x60098
 0x000000000000000a (STRSZ)              35118 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x46b8
 0x0000000000000019 (INIT_ARRAY)         0x5c298
 0x000000000000001b (INIT_ARRAYSZ)       80 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x5c288
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x000000006ffffff0 (VERSYM)             0x4148
 0x000000006ffffffe (VERNEED)            0x4678
 0x000000006fffffff (VERNEEDNUM)         2
 0x0000000000000000 (NULL)               0x0
```
## To Reproduce

1. build the project in termux-v0.118.0 (android) clang v17.0.6 cmake v3.28.3
2. it happens

## Expected behavior

an dlopen error will happen as the library is not appropriately linked

## OS

- Termux (aarch64-linux-android)

## Additional context

library can be used if the libpython is manually added back to the dynamic section by using `patchelf`

**Comment by ZCG-coder** [comment]
> Library can be used if the libpython is manually added back to the dynamic section by using `patchelf`

Can you please share the `patchelf` command? I think it would work when the command is added to the `CMakeLists.txt`, and manually patch the ELF after linking.

**Comment by 813ethan** [comment]
`patchelf --add-needed libpython3.11.so.1.0`
